# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comments_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
